name: Price Check

on:
  workflow_dispatch:

jobs:
  check-price:
    runs-on: ubuntu-latest

    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run price checker
        run: node check-price.js
